In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/covid_toy - covid_toy.csv")

In [4]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [ ]:
# If we want only top data then we will use head()

In [5]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
# If we want only last data then we will use tail()

In [6]:
df.tail()

    age  gender  fever   cough       city has_covid
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [8]:
df.shape

(100, 6)

In [9]:
df.sample(3) ### It will return the random data

    age  gender  fever   cough    city has_covid
42   27    Male  100.0    Mild   Delhi       Yes
27   33  Female  102.0  Strong   Delhi        No
80   14  Female   99.0    Mild  Mumbai       Yes

In [ ]:
# If we want to check total columns in a dataframe

In [10]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [ ]:
# If we want to check data type of columns

In [11]:
df.dtypes

age            int64
gender        object
fever        float64
cough         object
city          object
has_covid     object
dtype: object

In [ ]:
# If we want to check overall information then we can use df.info()

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [13]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [15]:
# Returns a new dataframe containing only categorical and object columns
categorical_df = df.select_dtypes(include=['category','object'])
categorical_df.columns.tolist()

['gender', 'cough', 'city', 'has_covid']

In [ ]:
#option-1

In [16]:
# Returns a new dataframe containing only integer columns
int_df = df.select_dtypes(include=['category','int'])
int_df.columns.tolist()

['age']

In [ ]:
#option-2

In [17]:
# Extract all integer columns(e.g. int16, int32, int64)
df_int = df.select_dtypes(include='int')
df_int.columns.tolist()

['age']

In [ ]:
df.head(2)

In [ ]:
# If we want to check missing data in a df then we will use df.isnull().sum()

In [18]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [19]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [20]:
df['fever'].mean()

np.float64(100.84444444444445)

In [21]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
# If i want to check total sub-categories in a column then we will use df.value_counts()

In [22]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [23]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64