In [7]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv("/content/placement - placement.csv")
df

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [9]:
df.head()

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [4]:
df.tail()

    cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [10]:
df.describe() ## statically view of data

           cgpa  resume_score      placed
count  100.0000    100.000000  100.000000
mean     6.9422      6.930500    0.500000
std      1.1192      0.979608    0.502519
min      5.2700      4.950000    0.000000
25%      5.9800      6.190000    0.000000
50%      6.6200      7.055000    0.500000
75%      8.0450      7.640000    1.000000
max      9.4000      9.060000    1.000000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [12]:
top_left_corner_df = df.iloc[:4 , :3] #iloc[row_range , column_range]
top_left_corner_df

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1

In [13]:
df.loc[1:3 , ["cgpa","placed"]] #loc[row_range, column_names]

   cgpa  placed
1  6.17       0
2  8.27       1
3  6.88       1

In [14]:
s = df.axes
s

[RangeIndex(start=0, stop=100, step=1),
 Index(['cgpa', 'resume_score', 'placed'], dtype='object')]

In [15]:
p = df.dtypes
p

cgpa            float64
resume_score    float64
placed            int64
dtype: object

In [17]:
df['cgpa'].dtypes

dtype('float64')

In [18]:
b = df.empty #it return true if there are any missing data in dataframe otherwise it will return false
b

False

In [19]:
df.isnull().sum() #for checking missing values

cgpa            0
resume_score    0
placed          0
dtype: int64

In [20]:
df = df.dropna() #for remove missing rows

In [21]:
i = df.ndim #number of axes(it is 2)
i

2

In [23]:
t = df.shape #shape = n(rows),n(columns)
t
df.shape[0] # total rows in data
df.shape[1] # total columns in data

3

In [ ]:
d = df.size #row count*column count
d

In [ ]:
a = df.values  #get a numpy array for df
a

In [ ]:
df = df.copy()

In [24]:
p = df.sort_values(by = "resume_score") #sorts in ascending order
p

    cgpa  resume_score  placed
94  8.01          4.95       1
87  5.62          5.05       0
13  8.50          5.09       1
41  8.68          5.15       1
1   6.17          5.17       0
..   ...           ...     ...
17  7.81          8.71       1
38  6.00          8.72       0
65  6.04          8.75       0
2   8.27          8.86       1
69  8.06          9.06       1

[100 rows x 3 columns]

In [25]:
r = df.sort_index() #index in ascending order
r

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [26]:
import pandas as pd

In [27]:
df = pd.read_csv("/content/Churn_Modelling - Churn_Modelling.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [28]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [29]:
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [30]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [32]:
top_left_corner_df = df.iloc[:4 , :3]
top_left_corner_df

   RowNumber  CustomerId   Surname
0          1    15634602  Hargrave
1          2    15647311      Hill
2          3    15619304      Onio
3          4    15701354      Boni

In [35]:
df.loc[1:3 , ["RowNumber","Age"]]

   RowNumber  Age
1          2   41
2          3   42
3          4   39

In [36]:
s = df.axes
s

[RangeIndex(start=0, stop=10000, step=1),
 Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
        'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
        'IsActiveMember', 'EstimatedSalary', 'Exited'],
       dtype='object')]

In [37]:
p = df.dtypes
p

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [38]:
b = df.empty
b

False

In [39]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [43]:
df = df.dropna()

In [44]:
i = df.ndim
i

2

In [45]:
t = df.shape
t

(10000, 14)

In [46]:
df.shape[0]
df.shape[1]

14

In [47]:
d = df.size
d

140000

In [48]:
a = df.values
a

array([[1, 15634602, 'Hargrave', ..., 1, 101348.88, 1],
       [2, 15647311, 'Hill', ..., 1, 112542.58, 0],
       [3, 15619304, 'Onio', ..., 0, 113931.57, 1],
       ...,
       [9998, 15584532, 'Liu', ..., 1, 42085.58, 1],
       [9999, 15682355, 'Sabbatini', ..., 0, 92888.52, 1],
       [10000, 15628319, 'Walker', ..., 0, 38190.78, 0]], dtype=object)

In [49]:
df = df.copy()

In [40]:
p = df.sort_values(by = "CustomerId")
p

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1287,1288,15565701,Ferri,698,Spain,Female,39,9,161993.89,1,0,0,90212.38,0
4198,4199,15565706,Akobundu,612,Spain,Male,35,1,0.00,1,1,1,83256.26,1
7090,7091,15565714,Cattaneo,601,France,Male,47,1,64430.06,2,0,1,96517.97,0
2020,2021,15565779,Kent,627,Germany,Female,30,6,57809.32,1,1,0,188258.49,0
3697,3698,15565796,Docherty,745,Germany,Male,48,10,96048.55,1,1,0,74510.65,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3411,3412,15815628,Moysey,711,France,Female,37,8,113899.92,1,0,0,80215.20,0
8271,8272,15815645,Akhtar,481,France,Male,37,8,152303.66,2,1,1,175082.20,0
8088,8089,15815656,Hopkins,541,Germany,Female,39,9,100116.67,1,1,1,199808.10,1
1762,1763,15815660,Mazzi,758,France,Female,34,1,154139.45,1,1,1,60728.89,0
5502,5503,15815690,Akabueze,614,Spain,Female,40,3,113348.50,1,1,1,77789.01,0

In [50]:
df[0:10]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [51]:
df.sort_values(by='Surname', ascending=False)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
7739,7740,15689952,Zuyeva,724,Spain,Male,41,5,0.00,1,0,1,115753.94,0
6385,6386,15706810,Zuyeva,606,Germany,Female,32,1,106301.85,2,0,1,59061.25,0
586,587,15722010,Zuyev,621,Spain,Male,53,9,170491.84,1,1,0,35588.07,1
6973,6974,15583394,Zuyev,659,Germany,Male,39,8,106259.63,2,1,1,198103.32,0
1030,1031,15681174,Zuev,730,France,Male,39,1,116537.60,1,0,0,145679.60,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2988,2989,15684801,Abbott,689,France,Male,47,1,93871.95,3,1,0,156878.42,1
6838,6839,15680804,Abbott,850,France,Male,29,6,0.00,2,1,1,10672.54,0
841,842,15737792,Abbie,818,France,Female,31,1,186796.37,1,0,0,178252.63,0
5109,5110,15576156,Abazu,710,Spain,Female,28,6,0.00,1,1,0,48426.98,0
3271,3272,15708791,Abazu,584,Spain,Male,32,9,85534.83,1,0,0,169137.24,0

In [56]:
df['Gender']

0       Female
1       Female
2       Female
3       Female
4       Female
         ...
9995      Male
9996      Male
9997    Female
9998      Male
9999    Female
Name: Gender, Length: 10000, dtype: object