In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/content/covid_toy - covid_toy.csv")

In [4]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [7]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [8]:
df['fever'].mean()

np.float64(100.84444444444445)

In [9]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [10]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [11]:
df['gender'] = df['gender'].map({'female':1, 'Male':0})

In [12]:
df.head(7)

   age  gender       fever   cough       city has_covid
0   60     0.0  103.000000    Mild    Kolkata        No
1   27     0.0  100.000000    Mild      Delhi       Yes
2   42     0.0  101.000000    Mild      Delhi        No
3   31     NaN   98.000000    Mild    Kolkata        No
4   65     NaN  101.000000    Mild     Mumbai        No
5   84     NaN  100.844444    Mild  Bangalore       Yes
6   14     0.0  101.000000  Strong  Bangalore        No

In [13]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [15]:
df['cough'] = df['cough'].map({'Mild':0, 'Strong':1})

In [16]:
df

    age  gender  fever  cough       city has_covid
0    60     0.0  103.0      0    Kolkata        No
1    27     0.0  100.0      0      Delhi       Yes
2    42     0.0  101.0      0      Delhi        No
3    31     NaN   98.0      0    Kolkata        No
4    65     NaN  101.0      0     Mumbai        No
..  ...     ...    ...    ...        ...       ...
95   12     NaN  104.0      0  Bangalore        No
96   51     NaN  101.0      1    Kolkata       Yes
97   20     NaN  101.0      0  Bangalore        No
98    5     NaN   98.0      1     Mumbai        No
99   10     NaN   98.0      1    Kolkata       Yes

[100 rows x 6 columns]

In [17]:
df['has_covid'].value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

In [18]:
df['has_covid'] = df['has_covid'].map({'Yes':1, 'No':0})

In [19]:
df.head()

   age  gender  fever  cough     city  has_covid
0   60     0.0  103.0      0  Kolkata          0
1   27     0.0  100.0      0    Delhi          1
2   42     0.0  101.0      0    Delhi          0
3   31     NaN   98.0      0  Kolkata          0
4   65     NaN  101.0      0   Mumbai          0

In [20]:
df.filter(items = ['gender','city'])

    gender       city
0      0.0    Kolkata
1      0.0      Delhi
2      0.0      Delhi
3      NaN    Kolkata
4      NaN     Mumbai
..     ...        ...
95     NaN  Bangalore
96     NaN    Kolkata
97     NaN  Bangalore
98     NaN     Mumbai
99     NaN    Kolkata

[100 rows x 2 columns]

In [21]:
df[['fever','has_covid']]

    fever  has_covid
0   103.0          0
1   100.0          1
2   101.0          0
3    98.0          0
4   101.0          0
..    ...        ...
95  104.0          0
96  101.0          1
97  101.0          0
98   98.0          0
99   98.0          1

[100 rows x 2 columns]

In [22]:
df.head(3)

   age  gender  fever  cough     city  has_covid
0   60     0.0  103.0      0  Kolkata          0
1   27     0.0  100.0      0    Delhi          1
2   42     0.0  101.0      0    Delhi          0

In [24]:
df['fever'] = df['fever'].astype(int)  ## using .astype() we can change datatype

In [25]:
df.head(3)

   age  gender  fever  cough     city  has_covid
0   60     0.0    103      0  Kolkata          0
1   27     0.0    100      0    Delhi          1
2   42     0.0    101      0    Delhi          0

In [26]:
df['age'] = df['age'].astype(float)

In [27]:
df.head(3)

    age  gender  fever  cough     city  has_covid
0  60.0     0.0    103      0  Kolkata          0
1  27.0     0.0    100      0    Delhi          1
2  42.0     0.0    101      0    Delhi          0

In [30]:
df['fever'][1:3] = 50

/tmp/ipykernel_2392/146693501.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['fever'][1:3] = 50
/tmp/ipykernel_2392/146693501.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['fever'][1:3] = 50

In [31]:
df.head(3)

    age  gender  fever  cough     city  has_covid
0  60.0     0.0    103      0  Kolkata          0
1  27.0     0.0     50      0    Delhi          1
2  42.0     0.0     50      0    Delhi          0

In [32]:
df['city'][0] = 'jaipur'

/tmp/ipykernel_2392/2306389173.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['city'][0] = 'jaipur'
/tmp/ipykernel_2392/2306389173.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'][0] = 'jaipur'

In [33]:
df.head(3)

    age  gender  fever  cough    city  has_covid
0  60.0     0.0    103      0  jaipur          0
1  27.0     0.0     50      0   Delhi          1
2  42.0     0.0     50      0   Delhi          0

In [37]:
df = df.rename(columns = {'cough':'updated_cough'}) #permanent changes in dataframe

In [38]:
df.rename(columns = {'fever':'updated_fever'}) #temporary changes in dataframe

     age  gender  updated_fever  updated_cough       city  has_covid
0   60.0     0.0            103              0     jaipur          0
1   27.0     0.0             50              0      Delhi          1
2   42.0     0.0             50              0      Delhi          0
3   31.0     NaN             98              0    Kolkata          0
4   65.0     NaN            101              0     Mumbai          0
..   ...     ...            ...            ...        ...        ...
95  12.0     NaN            104              0  Bangalore          0
96  51.0     NaN            101              1    Kolkata          1
97  20.0     NaN            101              0  Bangalore          0
98   5.0     NaN             98              1     Mumbai          0
99  10.0     NaN             98              1    Kolkata          1

[100 rows x 6 columns]

In [36]:
df.rename(columns = {'city':'updated_city'})

     age  gender  fever  cough updated_city  has_covid
0   60.0     0.0    103      0       jaipur          0
1   27.0     0.0     50      0        Delhi          1
2   42.0     0.0     50      0        Delhi          0
3   31.0     NaN     98      0      Kolkata          0
4   65.0     NaN    101      0       Mumbai          0
..   ...     ...    ...    ...          ...        ...
95  12.0     NaN    104      0    Bangalore          0
96  51.0     NaN    101      1      Kolkata          1
97  20.0     NaN    101      0    Bangalore          0
98   5.0     NaN     98      1       Mumbai          0
99  10.0     NaN     98      1      Kolkata          1

[100 rows x 6 columns]

In [39]:
df['city']

0        jaipur
1         Delhi
2         Delhi
3       Kolkata
4        Mumbai
        ...
95    Bangalore
96      Kolkata
97    Bangalore
98       Mumbai
99      Kolkata
Name: city, Length: 100, dtype: object

In [40]:
df['new_updated_city'] = df['city'].where(df['city'] == 'Delhi', other=0)

In [41]:
df.head(10)

    age  gender  fever  updated_cough       city  has_covid new_updated_city
0  60.0     0.0    103              0     jaipur          0                0
1  27.0     0.0     50              0      Delhi          1            Delhi
2  42.0     0.0     50              0      Delhi          0            Delhi
3  31.0     NaN     98              0    Kolkata          0                0
4  65.0     NaN    101              0     Mumbai          0                0
5  84.0     NaN    100              0  Bangalore          1                0
6  14.0     0.0    101              1  Bangalore          0                0
7  20.0     NaN    100              1     Mumbai          1                0
8  19.0     NaN    100              1  Bangalore          0                0
9  64.0     NaN    101              0      Delhi          0            Delhi

In [42]:
df['updated_has_covid'] = df['has_covid'].where(df['has_covid'] == 0, other='Positive')

In [43]:
df.head(10)

,age,gender,fever,updated_cough,city,has_covid,new_updated_city,updated_has_covid
0,60.0,0.0,103,0,jaipur,0,0,0
1,27.0,0.0,50,0,Delhi,1,Delhi,Positive
2,42.0,0.0,50,0,Delhi,0,Delhi,0
3,31.0,NaN,98,0,Kolkata,0,0,0
4,65.0,NaN,101,0,Mumbai,0,0,0
5,84.0,NaN,100,0,Bangalore,1,0,Positive
6,14.0,0.0,101,1,Bangalore,0,0,0
7,20.0,NaN,100,1,Mumbai,1,0,Positive
8,19.0,NaN,100,1,Bangalore,0,0,0
9,64.0,NaN,101,0,Delhi,0,Delhi,0

In [44]:
df.to_csv("covid_patients_record.csv", index = False)

In [45]:
df.to_excel("covid_phase_2.xlsx")