In [ ]:
#Introduction to numpy: It is open source library in python used for handling scientific calculations
"""Diff between list and numpy:
  1. List heterogeneous data type and numpy is homogeneous data type
  2. List takes more memory as compared to numpy
  3. List takes more execution time as compared to numpy"""

In [ ]:
import numpy as np

In [ ]:
a = [1,45,78,90]
type(a)

list

In [ ]:
import numpy as np
b = np.array(a)
b

array([ 1, 45, 78, 90])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
#user defined array
import numpy as np
a = []
size = int(input("enter the size: "))
for i in range(size):
  val = int(input("enter the item: "))
  a.append(val)
b = np.array(a)
b

enter the size: 2
enter the item: 11
enter the item: 22

array([11, 22])

In [ ]:
type(b)  #nd means n-directional array

numpy.ndarray

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#matrix --> rows and columns
#row1 = [1,2,3]
#row2 = [4,5,6]
#row3 = [7,8,9]

#col1 = [1,4,7]
#col2 = [2,5,8]
#col3 = [3,6,9]

#total elements: row*column = 3*3 = 9

In [ ]:
print("total rows and columns: ", b.shape)
print("total elements",b.size)

total rows and columns:  (3, 3)
total elements 9

In [ ]:
#how to check dimension of a array?
a = np.array([1,3,4])
a

array([1, 3, 4])

In [ ]:
a.ndim #n-dimension

1

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a.ndim

2

In [ ]:
a = np.array([[[1,2,3],[4,5,6]]])
a.ndim

3

In [ ]:
#why we are studying numpy?
#images --> pixels(0-255) --> normalize(0-1) --> matrix --> operations
#deep learning --> artificial neurons --> weight --> randomly creation --> numpy
#datasets --> dummy entry --> random module --> attach pandas

In [ ]:
#pre-defined functions in numpy
# 1. zeros() --> it will create an array in which all the values will be zero in either 1-D or multi-dimensional.
a = np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
a = np.zeros((3,4))
print(a)
a.shape

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

(3, 4)

In [ ]:
# 2.ones() --> it will create an array in which all the values will be 1 in either 1-D or multi-dimensional.
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [ ]:
a = np.ones((4,5))
print(a)
print(a.shape)
print(a.size)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(4, 5)
20

In [ ]:
# 3.eye() --> it will create an array in which diagonal positional elements will be 1 and rest will be 0.
import numpy as np
a = np.eye(3) #rows = col --> symmetrix matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.eye(3,4) #rows != col --> asymmetrix matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# 4.diag() --> it will create an array in which we can set our custom values at diagonal position.
a = np.diag([31,45,67,22])
a

array([[31,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 67,  0],
       [ 0,  0,  0, 22]])

In [ ]:
# 5.random module:
#   a.Randint() --> it will create an array randomly in a given range
#   syntax: np.random.randint(min_range,max_range,total_numbers)
a = np.random.randint(1,15,4)
a

array([14, 10,  9,  8])

In [ ]:
# b. rand() --> it will generate random numbers from 0 to 1.
# syntax: np.random.rand(total_random_numbers)
a = np.random.rand(4)
a

array([0.855995  , 0.29033366, 0.05541368, 0.55901511])

In [ ]:
#In .rand function there is some sort of problem to solve that problem the other function is introduced which is:
# c. seed() --> it will fix or lock our generated code.
#syntax: np.random.seed(45)
# a = np.random.randint(1,10,2)

In [ ]:
np.random.seed(45) #the value inside it can be any but it cannot be empty and the value is neccesary to lock the values and if we change the value of it the values will get unlocked and get changed
a = np.random.randint(1,10,4)
a

array([4, 1, 6, 4])

In [ ]:
#view v/s copy
#view means modifying the original data and copy means modifying the copied data which will not affect the original one

In [ ]:
 a = np.array([10,20,30,40,50,60,70,80])
 a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
b = a[1:4]
b[:] = 0
print(b)
print(a)

[0 0 0]
[10  0  0  0 50 60 70 80]

In [ ]:
#copy
a = np.array([10,20,30,40,50,60,70,80])
b = a[1:4].copy()
b[:] = 0
print(a)

[10 20 30 40 50 60 70 80]

In [ ]:
#Reshaping the array:
#condition --> total rows*col = total elements

In [ ]:
a = np.random.randint(1,50,12)
a

array([ 5, 16,  2, 15,  9, 24, 47,  9, 13, 35, 25, 13])

In [ ]:
#1*12,12*1
#3*4,4*3
#2*6,6*2

In [ ]:
a.reshape(2,6)

array([[ 5, 16,  2, 15,  9, 24],
       [47,  9, 13, 35, 25, 13]])

In [ ]:
a.reshape(3,4)

array([[ 5, 16,  2, 15],
       [ 9, 24, 47,  9],
       [13, 35, 25, 13]])

In [ ]:
# y = mx+b
# m = matrix --> weights
# x = values --> matrix

# matrix(col)*matrix(rows)

In [ ]:
a.shape

(12,)

In [ ]:
a.reshape(-1,3)

array([[ 5, 16,  2],
       [15,  9, 24],
       [47,  9, 13],
       [35, 25, 13]])

In [ ]:
a.reshape(2,-1)

array([[ 5, 16,  2, 15,  9, 24],
       [47,  9, 13, 35, 25, 13]])

In [ ]:
#operations on array
a = np.arange(1,5,2) #last one will be excluded
a

array([1, 3])

In [ ]:
a = np.arange(1,5)
a*2

array([2, 4, 6, 8])

In [ ]:
b = np.arange(5,9)
b

array([5, 6, 7, 8])

In [ ]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a*b

array([[ 5, 12],
       [21, 32]])

In [ ]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[5, 6],
       [7, 8]])

In [ ]:
# 1*5+2*7  1*6+2*8
a.dot(b) #this is for matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [ ]:
b = a>10
a[b]

array([11, 12, 13, 14])

In [ ]:
a = np.arange(1,4)
a**2

array([1, 4, 9])

In [ ]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(a)

np.int64(45)

In [ ]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
np.sum(a , axis = 1)  #axis = 1 means row wise operation

array([ 6, 15, 24])

In [ ]:
np.sum(a , axis = 0)  #axis = 0 means col wise operation

array([12, 15, 18])

In [ ]:
#Introduction to pandas:
#Pandas ia an open-source library of python which is used for handling data manipulations.

In [ ]:
import pandas as pd

In [ ]:
#Data structure of pandas:
# 1. Series
# 2. Data frame

In [ ]:
# 1.Series --> It is one dimensional array and it returns only values not column name.
import pandas as pd
a = pd.Series([3,45,78,98])
a

0     3
1    45
2    78
3    98
dtype: int64

In [ ]:
type(a)

pandas.core.series.Series

In [ ]:
#2. Data Frame --> It is multi-dimensional array and it returns only value with column name.

In [ ]:
# Task:: We have to create a dataframe of employess in which column are
# emp_id, emp_name, department, salary, working_hours

In [ ]:
b = {
    "Emp_ID": ['A101','A102','A103','A104','A105','A106'],
    "Emp_Name":['Sam','Rahul','Aniket','Gorav','Mohit','Karan'],
    "Department":['IT','Operations','IT','IT','Operations','IT'],
    "Salary" : [20000,25000,35000,21000,40000,45000],
    "Working_hours": [8,8,9,9,9,8]
}
type(b)

dict

In [ ]:
import pandas as pd
b = {
    "Emp_ID": ['A101','A102','A103','A104','A105','A106'],
    "Emp_Name":['Sam','Rahul','Aniket','Gorav','Mohit','Karan'],
    "Department":['IT','Operations','IT','IT','Operations','IT'],
    "Salary" : [20000,25000,35000,21000,40000,45000],
    "Working_hours": [8,8,9,9,9,8]

}
c = pd.DataFrame(b)
c

  Emp_ID Emp_Name  Department  Salary  Working_hours
0   A101      Sam          IT   20000              8
1   A102    Rahul  Operations   25000              8
2   A103   Aniket          IT   35000              9
3   A104    Gorav          IT   21000              9
4   A105    Mohit  Operations   40000              9
5   A106    Karan          IT   45000              8

In [ ]:
# How can we export our dataframe into CSV data?
c.to_csv("emp_info.csv") #go to the files and check

  Emp_ID Emp_Name  Department  Salary  Working_hours
0   A101      Sam          IT   20000              8
1   A102    Rahul  Operations   25000              8
2   A103   Aniket          IT   35000              9
3   A104    Gorav          IT   21000              9
4   A105    Mohit  Operations   40000              9
5   A106    Karan          IT   45000              8

In [ ]:
c.to_csv("new_emp_info.csv", index = False) #index = false means it will remove the unnamed column.
c

  Emp_ID Emp_Name  Department  Salary  Working_hours
0   A101      Sam          IT   20000              8
1   A102    Rahul  Operations   25000              8
2   A103   Aniket          IT   35000              9
3   A104    Gorav          IT   21000              9
4   A105    Mohit  Operations   40000              9
5   A106    Karan          IT   45000              8

In [ ]:
#How to import csv data using pandas

In [ ]:
c = pd.read_csv("/content/flipkart.csv")
c

,k7wcnx href,UCc1lI src,fU6cHR,RG5Slk,MKiFS6,PZfbSE src,PvbNMB,o2SIOJ,PvbNMB 2,DTBslk,...,DTBslk 5,DTBslk 6,hZ3P6w,kRYCnD,HQe8jr,HZ0E6r,HZ0E6r 2,HZ0E6r 3,HZ0E6r 4,qYp2rh src
0,https://www.flipkart.com/poco-c85-5g-power-bla...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"POCO C85 5G (Power Black, 128 GB)",3.8,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","1,611 Ratings",&,157 Reviews,4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,...,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Phone and 6 M...,"₹14,499","₹20,999",30% off,Upto,"₹10,000",Off on Exchange,Bank Offer,NaN
1,https://www.flipkart.com/vivo-t4-lite-5g-prism...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,Vivo T4 Lite 5G (Prism Blue 2026) ( 4GB 64GB),4.3,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","37,089 Ratings",&,"1,310 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,...,Dimensity 6300 5G Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹14,999","₹27,999",46% off,Upto,"₹10,350",Off on Exchange,Bank Offer,https://static-assets-web.flixcart.com/fk-p-li...
2,https://www.flipkart.com/poco-c85-5g-mystic-pu...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"POCO C85 5G (Mystic Purple, 128 GB)",3.8,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","1,611 Ratings",&,157 Reviews,4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,...,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Phone and 6 M...,"₹14,499","₹20,999",30% off,Upto,"₹10,000",Off on Exchange,Bank Offer,NaN
3,https://www.flipkart.com/vivo-t4-lite-5g-titan...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,Vivo T4 Lite 5G (Titanium Gold 2026) (4GB 64GB),4.3,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","37,089 Ratings",&,"1,310 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,...,Dimensity 6300 5G Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹14,999","₹27,999",46% off,Upto,"₹10,350",Off on Exchange,Bank Offer,https://static-assets-web.flixcart.com/fk-p-li...
4,https://www.flipkart.com/hmd-vibe2-5g-nordic-b...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"HMD Vibe2 5G (Nordic Blue, 128 GB)",4.6,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","2,426 Ratings",&,155 Reviews,4 GB RAM | 128 GB ROM,...,1-year manufacturer warranty,NaN,"₹14,999","₹19,999",25% off,Super Deals,Upto,"₹10,350",Off on Exchange,https://static-assets-web.flixcart.com/fk-p-li...
5,https://www.flipkart.com/hmd-vibe2-5g-cosmic-l...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"HMD Vibe2 5G (Cosmic Lavender, 128 GB)",4.6,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","2,426 Ratings",&,155 Reviews,4 GB RAM | 128 GB ROM,...,1-year manufacturer warranty,NaN,"₹14,999","₹19,999",25% off,Super Deals,Upto,"₹10,350",Off on Exchange,https://static-assets-web.flixcart.com/fk-p-li...
6,https://www.flipkart.com/oppo-k14x-5g-icy-blue...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"OPPO K14x 5G (Icy Blue, 64 GB)",4.3,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","4,548 Ratings",&,247 Reviews,4 GB RAM | 64 GB ROM,...,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹15,999","₹19,999",20% off,Upto,"₹11,050",Off on Exchange,Bank Offer,https://static-assets-web.flixcart.com/fk-p-li...
7,https://www.flipkart.com/samsung-galaxy-m17-5g...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"Samsung Galaxy M17 5G (Moonlight Silver, 128 GB)",4.2,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","1,311 Ratings",&,88 Reviews,4 GB RAM | 128 GB ROM,...,1 year manufacturer warranty for device and 6 ...,NaN,"₹14,580","₹17,999",18% off,Only few left,Bank Offer,NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...
8,https://www.flipkart.com/vivo-y11-5g-mystic-bl...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"vivo Y11 5G (Mystic Blue, 64 GB)",4.1,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...",143 Ratings,&,7 Reviews,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,...,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹14,999","₹39,999",62% off,Upto,"₹10,350",Off on Exchange,Bank Offer,https://static-assets-web.flixcart.com/fk-p-li...
9,https://www.flipkart.com/oppo-k14x-5g-prism-vi...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"OPPO K14x 5G (Prism Violet, 64 GB)",4.3,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","4,548 Ratings",&,247 Reviews,4 GB RAM | 64 GB ROM,...,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹15,999","₹19,999",20% off,Only few left,Upto,"₹11,050",Off on Exchange,https://static-assets-web.flixcart.com/fk-p-li...
10,https://www.flipkart.com/redmi-a7-pro-5g-black...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"REDMI A7 Pro 5G (Black, 128 GB)",4.1,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...",780 Ratings,&,44 Reviews,4 GB RAM | 128 GB ROM | Expandable Upto 128 GB,...,UNISOC T8300 octa-core processor Processor,1 year manufacturer warranty for device and 6 ...,"₹14,596","₹16,999",14% off,Only few left,Bank Offer,NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...
11,https://www.flipkart.com/realme-narzo-100-lite...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"realme Narzo 100 Lite 5G (Frost Silver, 128 GB)",4.1,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...",556 Ratings,&,27 Reviews,4 GB RAM | 128 GB ROM,...,1 year manufacturer warranty for device and 6 ...,NaN,"₹15,417","₹27,999",44% off,Only 1 left,Bank Offer,NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...
12,https://www.flipkart.com/realme-narzo-100-lite...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"realme Narzo 100 Lite 5G (Thunder Black, 64 GB)",4.1,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...",556 Ratings,&,27 Reviews,4 GB RAM | 64 GB ROM,...,1 year manufacturer warranty for device and 6 ...,NaN,"₹14,371","₹24,999",42% off,Bank Offer,NaN,NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...
13,https://www.flipkart.com/iqoo-z10-lite-5g-tita...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"IQOO Z10 Lite 5G (Titanium Blue, 64 GB)",4.2,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","3,587 Ratings",&,165 Reviews,4 GB RAM | 64 GB ROM,...,1 Year Warranty,NaN,"₹15,314","₹27,999",45% off,Only few left,Bank Offer,NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...
14,https://www.flipkart.com/samsung-galaxy-f06-5g...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"Samsung Galaxy F06 5G (Lit Violet, 128 GB)",4.2,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","46,866 Ratings",&,"2,960 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 1500 GB,...,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹13,999","₹16,999",17% off,Upto,"₹9,700",Off on Exchange,Bank Offer,https://static-assets-web.flixcart.com/fk-p-li...
15,https://www.flipkart.com/poco-c85x-elite-black...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"POCO C85x (Elite Black, 128 GB)",4.1,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","2,530 Ratings",&,118 Reviews,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,...,T8300 Processor,1 Year Manufacturer Warranty for Phone and 6 M...,"₹13,499","₹21,999",38% off,Upto,"₹9,400",Off on Exchange,Bank Offer,https://static-assets-web.flixcart.com/fk-p-li...
16,https://www.flipkart.com/poco-m7-pro-5g-olive-...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"POCO M7 Pro 5G (Olive Twilight, 128 GB)",4.3,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","38,770 Ratings",&,"2,901 Reviews",6 GB RAM | 128 GB ROM,...,Dimensity 7025 Ultra Processor,1 Year Manufacturer Warranty for Phone and 6 M...,"₹14,999","₹18,999",21% off,Upto,"₹10,350",Off on Exchange,Bank Offer,https://static-assets-web.flixcart.com/fk-p-li...
17,https://www.flipkart.com/iqoo-z10-lite-5g-cybe...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"IQOO Z10 Lite 5G (Cyber Green, 64 GB)",4.2,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","3,587 Ratings",&,165 Reviews,4 GB RAM | 64 GB ROM,...,1 Year Warranty,NaN,"₹15,444","₹15,999",3% off,Only 1 left,Bank Offer,NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...
18,https://www.flipkart.com/vivo-y11-5g-cosmic-go...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"vivo Y11 5G (Cosmic Gold, 64 GB)",4.1,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...",143 Ratings,&,7 Reviews,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,...,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹14,999","₹39,999",62% off,Upto,"₹10,350",Off on Exchange,Bank Offer,https://static-assets-web.flixcart.com/fk-p-li...
19,https://www.flipkart.com/poco-m7-5g-locked-air...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,POCO M7 5G - Locked with Airtel Prepaid (Ocean...,3.7,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","10,466 Ratings",&,500 Reviews,6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,...,4 Gen 2 5G Processor,1 Year Manufacturer Warranty for Phone and 6 M...,"₹12,999",NaN,NaN,Only few left,Upto,"₹8,900",Off on Exchange,NaN
20,https://www.flipkart.com/ai-nova-2-neo-5g-blac...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"Ai+ Nova 2 Neo 5G (Black, 128 GB)",NaN,NaN,NaN,NaN,NaN,6 GB RAM | 128 GB ROM | Expandable Upto 2 TB,...,Dimensity 6300 Processor,1 Year Warranty on Handset and 6 Months Warran...,"₹13,999","₹19,999",30% off,NaN,NaN,NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...
21,https://www.flipkart.com/redmi-a7-pro-5g-mist-...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"REDMI A7 Pro 5G (Mist Blue, 128 GB)",4.1,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...",780 Ratings,&,44 Reviews,4 GB RAM | 128 GB ROM | Expandable Upto 128 GB,...,UNISOC T8300 octa-core processor Processor,1 year manufacturer warranty for device and 6 ...,"₹14,550","₹16,999",14% off,Only few left,Bank Offer,NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...
22,https://www.flipkart.com/realme-narzo-100-lite...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"realme Narzo 100 Lite 5G (Thunder Black, 128 GB)",4.1,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...",556 Ratings,&,27 Reviews,4 GB RAM | 128 GB ROM,...,1 year manufacturer warranty for device and 6 ...,NaN,"₹15,523","₹27,999",44% off,Only few left,Bank Offer,NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...
23,https://www.flipkart.com/oppo-k14x-5g-prism-vi...,https://rukminim2.flixcart.com/image/312/312/x...,Add to Compare,"OPPO K14x 5G (Prism Violet, 128 GB)",4.3,"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0...","4,548 Ratings",&,247 Reviews,4 GB RAM | 128 GB ROM,...,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹17,999",NaN,NaN,Only few left,Upto,"₹12,650",Off on Exchange,https://static-assets-web.flixcart.com/fk-p-li...
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#task 1
c = pd.read_csv("/content/flipkart (1).csv")
c

,CIaYa1 href,MZeksS src,Fo1I0b,atJtCj,atJtCj href,Q3Sg7S src,hZ3P6w,CIaYa1 href 2,MZeksS src 2,Fo1I0b 2,...,Fo1I0b 4,atJtCj 4,atJtCj href 4,hZ3P6w 4,kRYCnD 3,HQe8jr 3,HZ0E6r 3,kRYCnD 4,HQe8jr 4,Q3Sg7S src 4
0,https://www.flipkart.com/dr-ortho-flexi-ease-w...,https://rukminim2.flixcart.com/image/612/612/x...,Dr. Ortho,Flexi Ease Women Shoes Casuals For Women,https://www.flipkart.com/dr-ortho-flexi-ease-w...,https://static-assets-web.flixcart.com/fk-p-li...,"₹2,342",https://www.flipkart.com/puma-carina-2-0-casua...,https://rukminim2.flixcart.com/image/612/612/x...,PUMA,...,SF,SFFASHIONSTORE Premium Hand crafted Boot for w...,https://www.flipkart.com/sf-sffashionstore-pre...,₹629,"₹1,999",68% off,Only few left,NaN,NaN,NaN
1,https://www.flipkart.com/dr-ortho-flexi-ease-w...,https://rukminim2.flixcart.com/image/612/612/x...,Dr. Ortho,Flexi Ease Women Shoes Casuals For Women,https://www.flipkart.com/dr-ortho-flexi-ease-w...,https://static-assets-web.flixcart.com/fk-p-li...,"₹2,342",https://www.flipkart.com/puma-softride-sophia-...,https://rukminim2.flixcart.com/image/612/612/x...,PUMA,...,PRIME STEP,Casuals For Women,https://www.flipkart.com/fabbmate-casuals-wome...,₹495,₹999,50% off,Only few left,NaN,NaN,NaN
2,https://www.flipkart.com/veximo-women-sneakers...,https://rukminim2.flixcart.com/image/612/612/x...,VEXIMO,Women Sneakers Stylish Lace Up Comfortable Cas...,https://www.flipkart.com/veximo-women-sneakers...,https://static-assets-web.flixcart.com/fk-p-li...,₹428,https://www.flipkart.com/puma-smashic-wmn-snea...,https://rukminim2.flixcart.com/image/612/612/x...,PUMA,...,PUMA,Casuals For Women,https://www.flipkart.com/dr-ortho-casuals-wome...,"₹3,600","₹2,499",11% off,"Buy 2 items, save extra 5%","₹7,999",54% off,NaN
3,https://www.flipkart.com/puma-x-ray-airflex-wn...,https://rukminim2.flixcart.com/image/612/612/x...,PUMA,X- Ray Airflex Wns Sneakers For Women,https://www.flipkart.com/puma-x-ray-airflex-wn...,https://static-assets-web.flixcart.com/fk-p-li...,"₹2,250",https://www.flipkart.com/skechers-d-lux-walker...,https://rukminim2.flixcart.com/image/612/612/x...,Skechers,...,Skechers,Canvas Shoes For Women,https://www.flipkart.com/streetfit-enterprises...,"₹2,314",₹999,57% off,Only few left,"₹5,499",57% off,NaN
4,https://www.flipkart.com/puma-smashic-wmn-casu...,https://rukminim2.flixcart.com/image/612/612/x...,PUMA,Smashic Wmn Casual Shoes For Women,https://www.flipkart.com/puma-smashic-wmn-casu...,https://static-assets-web.flixcart.com/fk-p-li...,"₹2,025",https://www.flipkart.com/puma-cali-court-luxe-...,https://rukminim2.flixcart.com/image/612/612/x...,PUMA,...,Sushi,Sneakers For Women,https://www.flipkart.com/sushi-sneakers-women/...,₹375,"₹5,999",54% off,Only few left,₹999,62% off,https://static-assets-web.flixcart.com/fk-p-li...
5,https://www.flipkart.com/cult-walking-shoes-wo...,https://rukminim2.flixcart.com/image/612/612/x...,Cult,Walking Shoes For Women,https://www.flipkart.com/cult-walking-shoes-wo...,https://static-assets-web.flixcart.com/fk-p-li...,"₹2,199",https://www.flipkart.com/puma-mostro-anodized-...,https://rukminim2.flixcart.com/image/612/612/x...,PUMA,...,Skechers,SUMMITS Walking Shoes For Women,https://www.flipkart.com/skechers-summits-walk...,"₹2,195","₹5,999",40% off,NaN,"₹4,999",56% off,https://static-assets-web.flixcart.com/fk-p-li...
6,https://www.flipkart.com/skechers-ultra-flex-w...,https://rukminim2.flixcart.com/image/612/612/x...,Skechers,ULTRA FLEX Walking Shoes For Women,https://www.flipkart.com/skechers-ultra-flex-w...,https://static-assets-web.flixcart.com/fk-p-li...,"₹2,635",https://www.flipkart.com/skechers-ultra-flex-w...,https://rukminim2.flixcart.com/image/612/612/x...,Skechers,...,Cult,Glidewave Running Shoes Enhanced Cushioning En...,https://www.flipkart.com/cult-glidewave-runnin...,"₹2,299","₹3,449",33% off,NaN,"₹3,659",37% off,https://static-assets-web.flixcart.com/fk-p-li...
7,https://www.flipkart.com/skechers-uno-stand-ai...,https://rukminim2.flixcart.com/image/612/612/x...,Skechers,Uno - Stand On Air Casual Shoes For Women,https://www.flipkart.com/skechers-uno-stand-ai...,https://static-assets-web.flixcart.com/fk-p-li...,"₹3,387",https://www.flipkart.com/ujaray-toe-women-whit...,https://rukminim2.flixcart.com/image/612/612/x...,UJARAY TOE,...,Cult,Women White Sneakers | Casual Shoes | Lightwei...,https://www.flipkart.com/ujaray-toe-women-whit...,"₹2,619","₹3,139",26% off,NaN,"₹3,879",32% off,NaN
8,https://www.flipkart.com/skechers-summits-walk...,https://rukminim2.flixcart.com/image/612/612/x...,Skechers,Summits Walking Shoes For Women,https://www.flipkart.com/skechers-summits-walk...,https://static-assets-web.flixcart.com/fk-p-li...,"₹2,195",https://www.flipkart.com/lotto-energex-running...,https://rukminim2.flixcart.com/image/612/612/x...,LOTTO,...,Layasa,New Fashion Comfort Heel Boot Boots For Women,https://www.flipkart.com/layasa-new-fashion-co...,₹581,"₹8,999",47% off,Only 5 left,"₹1,999",70% off,NaN
9,https://www.flipkart.com/cult-xypher-running-s...,https://rukminim2.flixcart.com/image/612/612/x...,Cult,SUMMITS Slip On Sneakers For Women,https://www.flipkart.com/skechers-summits-slip...,https://static-assets-web.flixcart.com/fk-p-li...,"₹2,549",https://www.flipkart.com/dr-ortho-casuals-wome...,https://rukminim2.flixcart.com/image/612/612/x...,Dr. Ortho,...,Skechers,Xypher Running Shoes Enhanced Cushioning Enhan...,https://www.flipkart.com/cult-xypher-running-s...,"₹2,195","₹5,799",50% off,"Buy 2 items, save extra 5%","₹4,999",56% off,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
c = pd.read_csv("/content/tripadvisor.csv")
c

,biGQs,biGQs 2,rmyCe href,biGQs 3,biGQs 4,biGQs 5,biGQs 6,biGQs 7,biGQs 8,biGQs 9,...,biGQs 89,biGQs 90,NhWcC src 20,biGQs 91,biGQs 92,UctUV 17,biGQs 93,f 20,biGQs 94,biGQs 95
0,Explore popular experiences,"See what other travellers like to do, based on...",https://www.tripadvisor.in/Attractions-g297689...,See all,Hiking Tours (24),Private Sightseeing Tours (23),Waterfalls (4),Photography Tours (3),Private and Luxury (25),Points of Interest & Landmarks (4),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Book these experiences for a close-up look at ...,See all,https://www.tripadvisor.in/Attractions-g297689...,Landour Infinity Walk - A Guided Walking Tour ...,5.0,(85),from per adult (price varies by group size),"₹2,000",Reserve,"Mussoorie: Kempty fall, Buddha temple & Gun hi...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,See all,Top Tibba Trek - Mussoorie,NaN,4.9,(63),from per adult (price varies by group size),"₹3,000",Benog Tibba Day Hike - Mussoorie,5.0,(42),...,from per adult,"₹5,000",https://dynamic-media-cdn.tripadvisor.com/medi...,Mussoorie Nature Walk Tour,3.0,3 of 5 bubbles,(2),Photo Shoots,from per adult,"₹1,500"
3,Map,See all,https://www.tripadvisor.in/Attractions-g297689...,"—we consider traveller reviews, ratings, numbe...",These are informed by Tripadvisor data,1. Lal Tibba Scenic Point,4.0,"(1,268)",Lookouts,By,...,1,See all,https://dynamic-media-cdn.tripadvisor.com/medi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Other Top Attractions around Mussoorie,Triveni Ghat,NaN,4.6,"(1,772)",45 km away,Religious Sites,Forest Research Institute,4.5,(707),...,16 km away,Parks,https://dynamic-media-cdn.tripadvisor.com/medi...,Tehri Dam,4.4,4.4 of 5 bubbles,(271),"New Tehri, India",4.6,(139)
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,See all,Landour Figure of Eight Walk,NaN,5.0,(5),from per adult,₹999,School Boy Walk,5.0,(13),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,See all,Nature's Trail: Dehradun to Mussoorie Private ...,NaN,5.0,(1),from per adult (price varies by group size),"₹7,558",Nag tibba Trek,5.0,(1),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,See all,Haunted walk,NaN,5.0,(3),from per adult,"₹1,500",Nature Walk of Mussoorie (2 Hours Guided Walki...,3.0,(2),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,See all,Discover Mussoorie: Private Guided Sightseeing...,NaN,5.0,(29),from per adult (price varies by group size),"₹8,000",Lal Tibba Sunset Walk,4.3,(6),...,from per adult (price varies by group size),"₹8,000",https://dynamic-media-cdn.tripadvisor.com/medi...,Night Treks & Haunted Walks - Mussoorie,5.0,5 of 5 bubbles,(3),Ghost Tours,from per adult,"₹4,000"
10,See all,Discover Dehradun: Private City Tour,NaN,5.0,(3),from per adult (price varies by group size),"₹8,000",11 Days Private Tour of Char Dham Yatra from D...,4.8,(36),...,from per adult,"₹1,400",https://dynamic-media-cdn.tripadvisor.com/medi...,Colonial Hill Station in North India,NaN,NaN,NaN,Multi-day Tours,from per adult (price varies by group size),"₹77,708"
11,See all,Valley of Flowers and Hemkund Himalayan Trek a...,NaN,5.0,(1),from per adult (price varies by group size),"₹17,999",Chardham Luxury Yatra Gangotri Yamunotri Kedar...,5.0,(1),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,See all,Bhadraj Temple Trek,NaN,5.0,(42),from per adult,"₹1,400",Benog Tibba Day Hike - Mussoorie,4.8,(11),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Free things to do in Mussoorie,See all,NaN,Lal Tibba Scenic Point,4.0,"(1,268)",Landour,4.0,(69),Kempty Falls,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd
c = pd.read_csv("/content/classroom.csv")
c

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
5    84  Female    NaN    Mild  Bangalore       Yes
6    14    Male  101.0  Strong  Bangalore        No
7    20  Female    NaN  Strong     Mumbai       Yes
8    19  Female  100.0  Strong  Bangalore        No
9    64  Female  101.0    Mild      Delhi        No
10   75  Female    NaN    Mild      Delhi        No
11   65  Female   98.0    Mild     Mumbai       Yes
12   25  Female   99.0  Strong    Kolkata        No
13   64    Male  102.0    Mild  Bangalore       Yes
14   51    Male  104.0    Mild  Bangalore        No
15   70    Male  103.0  Strong    Kolkata       Yes
16   69  Female  103.0    Mild    Kolkata       Yes
17   40  Female   98.0  Strong      Delhi        No
18   64  Female   98.0    Mild  Bangalore       Yes
19   42  Female    NaN  Strong  Bangalore       Yes
20   12    Male   98.0  Strong  Bangalore        No
21   73    Male   98.0    Mild  Bangalore       Yes
22   71  Female   98.0  Strong    Kolkata       Yes
23   80  Female   98.0    Mild      Delhi       Yes
24   13  Female  100.0  Strong    Kolkata        No
25   23    Male    NaN    Mild     Mumbai        No
26   19  Female  100.0    Mild    Kolkata       Yes
27   33  Female  102.0  Strong      Delhi        No
28   16    Male  104.0    Mild    Kolkata        No
29   34  Female    NaN  Strong     Mumbai       Yes
30   15    Male  101.0    Mild      Delhi       Yes
31   83    Male  103.0    Mild    Kolkata        No
32   34  Female  101.0  Strong      Delhi       Yes
33   26  Female   98.0    Mild    Kolkata        No
34   74    Male  102.0    Mild     Mumbai       Yes
35   82  Female  102.0  Strong  Bangalore        No
36   38  Female  101.0    Mild  Bangalore        No
37   55    Male  100.0    Mild    Kolkata        No
38   49  Female  101.0    Mild      Delhi       Yes
39   50  Female  103.0    Mild    Kolkata        No
40   49  Female  102.0    Mild      Delhi        No
41   82    Male    NaN    Mild    Kolkata       Yes
42   27    Male  100.0    Mild      Delhi       Yes
43   22  Female   99.0    Mild  Bangalore       Yes
44   20    Male  102.0  Strong      Delhi        No
45   72    Male   99.0    Mild  Bangalore        No
46   19  Female  101.0    Mild     Mumbai        No
47   18  Female  104.0    Mild  Bangalore        No
48   66    Male   99.0  Strong  Bangalore        No

In [ ]:
#how can we check total columns in this dataframe

In [ ]:
c.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [ ]:
#How can we check the top 5 data from the dataframe?

In [ ]:
c.head(8) #It will return top 5 data  by default and if pass value in it will return that rows.

   age  gender  fever   cough       city has_covid
0   60    Male  103.0    Mild    Kolkata        No
1   27    Male  100.0    Mild      Delhi       Yes
2   42    Male  101.0    Mild      Delhi        No
3   31  Female   98.0    Mild    Kolkata        No
4   65  Female  101.0    Mild     Mumbai        No
5   84  Female    NaN    Mild  Bangalore       Yes
6   14    Male  101.0  Strong  Bangalore        No
7   20  Female    NaN  Strong     Mumbai       Yes

In [ ]:
#How can we check bottom data from the dataframe?

In [ ]:
c.tail(8) #same concept as head

    age  gender  fever   cough       city has_covid
41   82    Male    NaN    Mild    Kolkata       Yes
42   27    Male  100.0    Mild      Delhi       Yes
43   22  Female   99.0    Mild  Bangalore       Yes
44   20    Male  102.0  Strong      Delhi        No
45   72    Male   99.0    Mild  Bangalore        No
46   19  Female  101.0    Mild     Mumbai        No
47   18  Female  104.0    Mild  Bangalore        No
48   66    Male   99.0  Strong  Bangalore        No

In [ ]:
c.sample()

    age  gender  fever cough       city has_covid
10   75  Female    NaN  Mild      Delhi        No
14   51    Male  104.0  Mild  Bangalore        No
39   50  Female  103.0  Mild    Kolkata        No

In [ ]:
#how can we check datatype of all columns

In [ ]:
c.dtypes

age            int64
gender        object
fever        float64
cough         object
city          object
has_covid     object
dtype: object

In [ ]:
#How can we check statically view of dataframe?

In [ ]:
c.describe()

             age       fever
count  49.000000   42.000000
mean   45.836735  100.619048
std    23.578192    1.912123
min    12.000000   98.000000
25%    23.000000   99.000000
50%    42.000000  101.000000
75%    66.000000  102.000000
max    84.000000  104.000000

In [ ]:
#how can we check overall information in the dataframe?

In [ ]:
c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        49 non-null     int64
 1   gender     49 non-null     object
 2   fever      42 non-null     float64
 3   cough      49 non-null     object
 4   city       49 non-null     object
 5   has_covid  49 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 2.4+ KB

In [ ]:
#how can we check missing values in a dataframe?

In [ ]:
c.isnull().sum()

age          0
gender       0
fever        7
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
c["fever"].mean()

np.float64(100.61904761904762)

In [ ]:
c["fever"] = c["fever"].fillna(c["fever"].mean())
c.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
#how can we check total sub-categories in a column

In [ ]:
c["gender"].value_counts()

gender
Female    29
Male      20
Name: count, dtype: int64

In [ ]:
c["cough"].value_counts()

cough
Mild      33
Strong    16
Name: count, dtype: int64

In [ ]:
c["city"].value_counts()

city
Bangalore    15
Kolkata      14
Delhi        13
Mumbai        7
Name: count, dtype: int64

In [ ]:
c["has_covid"].value_counts()

has_covid
No     28
Yes    21
Name: count, dtype: int64

In [ ]:
c.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
c["gender"] = c["gender"].map({"Male":0, "female":1})
c

    age  gender       fever   cough       city has_covid
0    60     0.0  103.000000    Mild    Kolkata        No
1    27     0.0  100.000000    Mild      Delhi       Yes
2    42     0.0  101.000000    Mild      Delhi        No
3    31     NaN   98.000000    Mild    Kolkata        No
4    65     NaN  101.000000    Mild     Mumbai        No
5    84     NaN  100.619048    Mild  Bangalore       Yes
6    14     0.0  101.000000  Strong  Bangalore        No
7    20     NaN  100.619048  Strong     Mumbai       Yes
8    19     NaN  100.000000  Strong  Bangalore        No
9    64     NaN  101.000000    Mild      Delhi        No
10   75     NaN  100.619048    Mild      Delhi        No
11   65     NaN   98.000000    Mild     Mumbai       Yes
12   25     NaN   99.000000  Strong    Kolkata        No
13   64     0.0  102.000000    Mild  Bangalore       Yes
14   51     0.0  104.000000    Mild  Bangalore        No
15   70     0.0  103.000000  Strong    Kolkata       Yes
16   69     NaN  103.000000    Mild    Kolkata       Yes
17   40     NaN   98.000000  Strong      Delhi        No
18   64     NaN   98.000000    Mild  Bangalore       Yes
19   42     NaN  100.619048  Strong  Bangalore       Yes
20   12     0.0   98.000000  Strong  Bangalore        No
21   73     0.0   98.000000    Mild  Bangalore       Yes
22   71     NaN   98.000000  Strong    Kolkata       Yes
23   80     NaN   98.000000    Mild      Delhi       Yes
24   13     NaN  100.000000  Strong    Kolkata        No
25   23     0.0  100.619048    Mild     Mumbai        No
26   19     NaN  100.000000    Mild    Kolkata       Yes
27   33     NaN  102.000000  Strong      Delhi        No
28   16     0.0  104.000000    Mild    Kolkata        No
29   34     NaN  100.619048  Strong     Mumbai       Yes
30   15     0.0  101.000000    Mild      Delhi       Yes
31   83     0.0  103.000000    Mild    Kolkata        No
32   34     NaN  101.000000  Strong      Delhi       Yes
33   26     NaN   98.000000    Mild    Kolkata        No
34   74     0.0  102.000000    Mild     Mumbai       Yes
35   82     NaN  102.000000  Strong  Bangalore        No
36   38     NaN  101.000000    Mild  Bangalore        No
37   55     0.0  100.000000    Mild    Kolkata        No
38   49     NaN  101.000000    Mild      Delhi       Yes
39   50     NaN  103.000000    Mild    Kolkata        No
40   49     NaN  102.000000    Mild      Delhi        No
41   82     0.0  100.619048    Mild    Kolkata       Yes
42   27     0.0  100.000000    Mild      Delhi       Yes
43   22     NaN   99.000000    Mild  Bangalore       Yes
44   20     0.0  102.000000  Strong      Delhi        No
45   72     0.0   99.000000    Mild  Bangalore        No
46   19     NaN  101.000000    Mild     Mumbai        No
47   18     NaN  104.000000    Mild  Bangalore        No
48   66     0.0   99.000000  Strong  Bangalore        No

In [ ]:
c["cough"] = c["cough"].map({"Mild":0, "Strong":1})
c

    age  gender       fever  cough       city has_covid
0    60     0.0  103.000000      0    Kolkata        No
1    27     0.0  100.000000      0      Delhi       Yes
2    42     0.0  101.000000      0      Delhi        No
3    31     NaN   98.000000      0    Kolkata        No
4    65     NaN  101.000000      0     Mumbai        No
5    84     NaN  100.619048      0  Bangalore       Yes
6    14     0.0  101.000000      1  Bangalore        No
7    20     NaN  100.619048      1     Mumbai       Yes
8    19     NaN  100.000000      1  Bangalore        No
9    64     NaN  101.000000      0      Delhi        No
10   75     NaN  100.619048      0      Delhi        No
11   65     NaN   98.000000      0     Mumbai       Yes
12   25     NaN   99.000000      1    Kolkata        No
13   64     0.0  102.000000      0  Bangalore       Yes
14   51     0.0  104.000000      0  Bangalore        No
15   70     0.0  103.000000      1    Kolkata       Yes
16   69     NaN  103.000000      0    Kolkata       Yes
17   40     NaN   98.000000      1      Delhi        No
18   64     NaN   98.000000      0  Bangalore       Yes
19   42     NaN  100.619048      1  Bangalore       Yes
20   12     0.0   98.000000      1  Bangalore        No
21   73     0.0   98.000000      0  Bangalore       Yes
22   71     NaN   98.000000      1    Kolkata       Yes
23   80     NaN   98.000000      0      Delhi       Yes
24   13     NaN  100.000000      1    Kolkata        No
25   23     0.0  100.619048      0     Mumbai        No
26   19     NaN  100.000000      0    Kolkata       Yes
27   33     NaN  102.000000      1      Delhi        No
28   16     0.0  104.000000      0    Kolkata        No
29   34     NaN  100.619048      1     Mumbai       Yes
30   15     0.0  101.000000      0      Delhi       Yes
31   83     0.0  103.000000      0    Kolkata        No
32   34     NaN  101.000000      1      Delhi       Yes
33   26     NaN   98.000000      0    Kolkata        No
34   74     0.0  102.000000      0     Mumbai       Yes
35   82     NaN  102.000000      1  Bangalore        No
36   38     NaN  101.000000      0  Bangalore        No
37   55     0.0  100.000000      0    Kolkata        No
38   49     NaN  101.000000      0      Delhi       Yes
39   50     NaN  103.000000      0    Kolkata        No
40   49     NaN  102.000000      0      Delhi        No
41   82     0.0  100.619048      0    Kolkata       Yes
42   27     0.0  100.000000      0      Delhi       Yes
43   22     NaN   99.000000      0  Bangalore       Yes
44   20     0.0  102.000000      1      Delhi        No
45   72     0.0   99.000000      0  Bangalore        No
46   19     NaN  101.000000      0     Mumbai        No
47   18     NaN  104.000000      0  Bangalore        No
48   66     0.0   99.000000      1  Bangalore        No

In [ ]:
c["city"] = c["city"].map({"Kolkata":0, "Banglore":1, "Delhi":2, "Mumbai":3})

   age  gender  fever  cough  city has_covid
0   60     0.0  103.0      0   NaN        No
1   27     0.0  100.0      0   NaN       Yes

In [ ]:
c["has_covid"] = c["has_covid"].map({"No":0, "Yes":1})

In [ ]:
c

    age  gender       fever  cough  city  has_covid
0    60     0.0  103.000000      0   NaN          0
1    27     0.0  100.000000      0   NaN          1
2    42     0.0  101.000000      0   NaN          0
3    31     NaN   98.000000      0   NaN          0
4    65     NaN  101.000000      0   NaN          0
5    84     NaN  100.619048      0   NaN          1
6    14     0.0  101.000000      1   NaN          0
7    20     NaN  100.619048      1   NaN          1
8    19     NaN  100.000000      1   NaN          0
9    64     NaN  101.000000      0   NaN          0
10   75     NaN  100.619048      0   NaN          0
11   65     NaN   98.000000      0   NaN          1
12   25     NaN   99.000000      1   NaN          0
13   64     0.0  102.000000      0   NaN          1
14   51     0.0  104.000000      0   NaN          0
15   70     0.0  103.000000      1   NaN          1
16   69     NaN  103.000000      0   NaN          1
17   40     NaN   98.000000      1   NaN          0
18   64     NaN   98.000000      0   NaN          1
19   42     NaN  100.619048      1   NaN          1
20   12     0.0   98.000000      1   NaN          0
21   73     0.0   98.000000      0   NaN          1
22   71     NaN   98.000000      1   NaN          1
23   80     NaN   98.000000      0   NaN          1
24   13     NaN  100.000000      1   NaN          0
25   23     0.0  100.619048      0   NaN          0
26   19     NaN  100.000000      0   NaN          1
27   33     NaN  102.000000      1   NaN          0
28   16     0.0  104.000000      0   NaN          0
29   34     NaN  100.619048      1   NaN          1
30   15     0.0  101.000000      0   NaN          1
31   83     0.0  103.000000      0   NaN          0
32   34     NaN  101.000000      1   NaN          1
33   26     NaN   98.000000      0   NaN          0
34   74     0.0  102.000000      0   NaN          1
35   82     NaN  102.000000      1   NaN          0
36   38     NaN  101.000000      0   NaN          0
37   55     0.0  100.000000      0   NaN          0
38   49     NaN  101.000000      0   NaN          1
39   50     NaN  103.000000      0   NaN          0
40   49     NaN  102.000000      0   NaN          0
41   82     0.0  100.619048      0   NaN          1
42   27     0.0  100.000000      0   NaN          1
43   22     NaN   99.000000      0   NaN          1
44   20     0.0  102.000000      1   NaN          0
45   72     0.0   99.000000      0   NaN          0
46   19     NaN  101.000000      0   NaN          0
47   18     NaN  104.000000      0   NaN          0
48   66     0.0   99.000000      1   NaN          0

In [ ]:
#Data -->
# 1.Categorical(Descrete) --> We cannot divide further. eg --> has_covid(y,n) , marital_status(y,n) ,result(p,f)
# 2.Numerical(Continuous) --> We can divide further. eg --> distance from jaipur to delhi(310.60km) , weight(kg,gm), salary(rupees)

In [ ]:
import pandas as pd
c = pd.read_csv("/content/classroom.csv")

In [ ]:
c.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [ ]:
c.isnull().sum()

age          0
gender       0
fever        7
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
c["fever"] = c["fever"].fillna(c["fever"].mean())
c.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
#Loc and Iloc
#c.loc[row_range, column_name] --> includes both the starting and ending value
#c.Iloc[row_range,column_range] --> includes starting value but exclude the last one

In [ ]:
c.loc[5:10]

    age  gender       fever   cough       city has_covid
5    84  Female  100.619048    Mild  Bangalore       Yes
6    14    Male  101.000000  Strong  Bangalore        No
7    20  Female  100.619048  Strong     Mumbai       Yes
8    19  Female  100.000000  Strong  Bangalore        No
9    64  Female  101.000000    Mild      Delhi        No
10   75  Female  100.619048    Mild      Delhi        No

In [ ]:
c.loc[5:10 ,["age","fever","cough"]]

    age       fever   cough
5    84  100.619048    Mild
6    14  101.000000  Strong
7    20  100.619048  Strong
8    19  100.000000  Strong
9    64  101.000000    Mild
10   75  100.619048    Mild

In [ ]:
c.iloc[5:10]

   age  gender       fever   cough       city has_covid
5   84  Female  100.619048    Mild  Bangalore       Yes
6   14    Male  101.000000  Strong  Bangalore        No
7   20  Female  100.619048  Strong     Mumbai       Yes
8   19  Female  100.000000  Strong  Bangalore        No
9   64  Female  101.000000    Mild      Delhi        No

In [ ]:
c.iloc[5:10, [0,1,2]] #indexing

   age  gender       fever
5   84  Female  100.619048
6   14    Male  101.000000
7   20  Female  100.619048
8   19  Female  100.000000
9   64  Female  101.000000

In [ ]:
c.iloc[5:10, [0,2]] = 55
c.head(11)

NameError: name 'c' is not defined

In [ ]:
c.head(2)

NameError: name 'c' is not defined

In [ ]:
#how to drop or delete a column

In [ ]:
#c.drop(columns = ['city']) #it will be only shown as a copy but original data will not get affected

In [ ]:
c = c.drop(columns = ["city"]) #now the original data will be affected and in every case this is only the way to update the original data

KeyError: "['city'] not found in axis"

In [ ]:
c

    age  gender  fever   cough has_covid
0    60    Male  103.0    Mild        No
1    27    Male  100.0    Mild       Yes
2    42    Male  101.0    Mild        No
3    31  Female   98.0    Mild        No
4    65  Female  101.0    Mild        No
5    84  Female    NaN    Mild       Yes
6    14    Male  101.0  Strong        No
7    20  Female    NaN  Strong       Yes
8    19  Female  100.0  Strong        No
9    64  Female  101.0    Mild        No
10   75  Female    NaN    Mild        No
11   65  Female   98.0    Mild       Yes
12   25  Female   99.0  Strong        No
13   64    Male  102.0    Mild       Yes
14   51    Male  104.0    Mild        No
15   70    Male  103.0  Strong       Yes
16   69  Female  103.0    Mild       Yes
17   40  Female   98.0  Strong        No
18   64  Female   98.0    Mild       Yes
19   42  Female    NaN  Strong       Yes
20   12    Male   98.0  Strong        No
21   73    Male   98.0    Mild       Yes
22   71  Female   98.0  Strong       Yes
23   80  Female   98.0    Mild       Yes
24   13  Female  100.0  Strong        No
25   23    Male    NaN    Mild        No
26   19  Female  100.0    Mild       Yes
27   33  Female  102.0  Strong        No
28   16    Male  104.0    Mild        No
29   34  Female    NaN  Strong       Yes
30   15    Male  101.0    Mild       Yes
31   83    Male  103.0    Mild        No
32   34  Female  101.0  Strong       Yes
33   26  Female   98.0    Mild        No
34   74    Male  102.0    Mild       Yes
35   82  Female  102.0  Strong        No
36   38  Female  101.0    Mild        No
37   55    Male  100.0    Mild        No
38   49  Female  101.0    Mild       Yes
39   50  Female  103.0    Mild        No
40   49  Female  102.0    Mild        No
41   82    Male    NaN    Mild       Yes
42   27    Male  100.0    Mild       Yes
43   22  Female   99.0    Mild       Yes
44   20    Male  102.0  Strong        No
45   72    Male   99.0    Mild        No
46   19  Female  101.0    Mild        No
47   18  Female  104.0    Mild        No
48   66    Male   99.0  Strong        No

In [ ]:
c.sort_index() #sort the data

    age  gender  fever   cough has_covid
0    60    Male  103.0    Mild        No
1    27    Male  100.0    Mild       Yes
2    42    Male  101.0    Mild        No
3    31  Female   98.0    Mild        No
4    65  Female  101.0    Mild        No
5    84  Female    NaN    Mild       Yes
6    14    Male  101.0  Strong        No
7    20  Female    NaN  Strong       Yes
8    19  Female  100.0  Strong        No
9    64  Female  101.0    Mild        No
10   75  Female    NaN    Mild        No
11   65  Female   98.0    Mild       Yes
12   25  Female   99.0  Strong        No
13   64    Male  102.0    Mild       Yes
14   51    Male  104.0    Mild        No
15   70    Male  103.0  Strong       Yes
16   69  Female  103.0    Mild       Yes
17   40  Female   98.0  Strong        No
18   64  Female   98.0    Mild       Yes
19   42  Female    NaN  Strong       Yes
20   12    Male   98.0  Strong        No
21   73    Male   98.0    Mild       Yes
22   71  Female   98.0  Strong       Yes
23   80  Female   98.0    Mild       Yes
24   13  Female  100.0  Strong        No
25   23    Male    NaN    Mild        No
26   19  Female  100.0    Mild       Yes
27   33  Female  102.0  Strong        No
28   16    Male  104.0    Mild        No
29   34  Female    NaN  Strong       Yes
30   15    Male  101.0    Mild       Yes
31   83    Male  103.0    Mild        No
32   34  Female  101.0  Strong       Yes
33   26  Female   98.0    Mild        No
34   74    Male  102.0    Mild       Yes
35   82  Female  102.0  Strong        No
36   38  Female  101.0    Mild        No
37   55    Male  100.0    Mild        No
38   49  Female  101.0    Mild       Yes
39   50  Female  103.0    Mild        No
40   49  Female  102.0    Mild        No
41   82    Male    NaN    Mild       Yes
42   27    Male  100.0    Mild       Yes
43   22  Female   99.0    Mild       Yes
44   20    Male  102.0  Strong        No
45   72    Male   99.0    Mild        No
46   19  Female  101.0    Mild        No
47   18  Female  104.0    Mild        No
48   66    Male   99.0  Strong        No

In [ ]:
c.rename(columns = {"cough":"updated_cough"})

    age  gender  fever updated_cough has_covid
0    60    Male  103.0          Mild        No
1    27    Male  100.0          Mild       Yes
2    42    Male  101.0          Mild        No
3    31  Female   98.0          Mild        No
4    65  Female  101.0          Mild        No
5    84  Female    NaN          Mild       Yes
6    14    Male  101.0        Strong        No
7    20  Female    NaN        Strong       Yes
8    19  Female  100.0        Strong        No
9    64  Female  101.0          Mild        No
10   75  Female    NaN          Mild        No
11   65  Female   98.0          Mild       Yes
12   25  Female   99.0        Strong        No
13   64    Male  102.0          Mild       Yes
14   51    Male  104.0          Mild        No
15   70    Male  103.0        Strong       Yes
16   69  Female  103.0          Mild       Yes
17   40  Female   98.0        Strong        No
18   64  Female   98.0          Mild       Yes
19   42  Female    NaN        Strong       Yes
20   12    Male   98.0        Strong        No
21   73    Male   98.0          Mild       Yes
22   71  Female   98.0        Strong       Yes
23   80  Female   98.0          Mild       Yes
24   13  Female  100.0        Strong        No
25   23    Male    NaN          Mild        No
26   19  Female  100.0          Mild       Yes
27   33  Female  102.0        Strong        No
28   16    Male  104.0          Mild        No
29   34  Female    NaN        Strong       Yes
30   15    Male  101.0          Mild       Yes
31   83    Male  103.0          Mild        No
32   34  Female  101.0        Strong       Yes
33   26  Female   98.0          Mild        No
34   74    Male  102.0          Mild       Yes
35   82  Female  102.0        Strong        No
36   38  Female  101.0          Mild        No
37   55    Male  100.0          Mild        No
38   49  Female  101.0          Mild       Yes
39   50  Female  103.0          Mild        No
40   49  Female  102.0          Mild        No
41   82    Male    NaN          Mild       Yes
42   27    Male  100.0          Mild       Yes
43   22  Female   99.0          Mild       Yes
44   20    Male  102.0        Strong        No
45   72    Male   99.0          Mild        No
46   19  Female  101.0          Mild        No
47   18  Female  104.0          Mild        No
48   66    Male   99.0        Strong        No

In [ ]:
c.iloc[2:5 , 0:4]

   age  gender  fever cough
2   42    Male  101.0  Mild
3   31  Female   98.0  Mild
4   65  Female  101.0  Mild

In [ ]:
c["Age"] = c["age"].add(10) #it is case sensitive and by default it will add a new column and not modify the values in that column
c.head(2)

   age gender  fever cough has_covid  Age
0   60   Male  103.0  Mild        No   70
1   27   Male  100.0  Mild       Yes   37

In [ ]:
c["fever"] = c["fever"].sub(100)
c.head(4)

   age  gender  fever cough has_covid  Age
0   60    Male    3.0  Mild        No   70
1   27    Male    0.0  Mild       Yes   37
2   42    Male    1.0  Mild        No   52
3   31  Female   -2.0  Mild        No   41

In [ ]:
c.head(5)

   age  gender  fever cough has_covid  Age
0   60    Male  103.0  Mild        No   70
1   27    Male  100.0  Mild       Yes   37
2   42    Male  101.0  Mild        No   52
3   31  Female   98.0  Mild        No   41
4   65  Female  101.0  Mild        No   75

In [ ]:
c[["age","fever"]] #using this method we can filter the data

    age  fever
0    60    3.0
1    27    0.0
2    42    1.0
3    31   -2.0
4    65    1.0
5    84    NaN
6    14    1.0
7    20    NaN
8    19    0.0
9    64    1.0
10   75    NaN
11   65   -2.0
12   25   -1.0
13   64    2.0
14   51    4.0
15   70    3.0
16   69    3.0
17   40   -2.0
18   64   -2.0
19   42    NaN
20   12   -2.0
21   73   -2.0
22   71   -2.0
23   80   -2.0
24   13    0.0
25   23    NaN
26   19    0.0
27   33    2.0
28   16    4.0
29   34    NaN
30   15    1.0
31   83    3.0
32   34    1.0
33   26   -2.0
34   74    2.0
35   82    2.0
36   38    1.0
37   55    0.0
38   49    1.0
39   50    3.0
40   49    2.0
41   82    NaN
42   27    0.0
43   22   -1.0
44   20    2.0
45   72   -1.0
46   19    1.0
47   18    4.0
48   66   -1.0